"""empty message

Revision ID: 9381d3e010f5
Revises: d2cbaa704c58
Create Date: 2026-01-19 14:47:41.464185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9381d3e010f5'
down_revision = 'd2cbaa704c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('snapshot_price')

    # ### end Alembic commands ###
